### ISSUE TITLE
Press and hold down key

### ISSUE THREAD

**Issue by gitolicious** [dmamontov/esphome-blekeyboard#18]
**Describe the bug**
How can I press and hold a key? For example I would like to hold down the space bar for five seconds. Would have expected this to work:

```yaml
button:
  - platform: template
    name: "Hold Space"
    id: hold_space
    on_press:
      then:
      - ble_keyboard.press:
          id: myblekeyboard
          code: 0x20 # space
      - delay: 5000ms
      - ble_keyboard.release: myblekeyboard
```
It results in just the space bar being sent and immediately relesed. Did I misunderstand the `press` function in that it doesn't hold down the key until `release` is called? When would you use the `release` function otherwise?
 
**Please complete the following information:**
 - ESPHome version: 2022.11.5
 - Component version: latest? _(how to find out? I simply put `source: github://dmamontov/esphome-blekeyboard`)_

**Comment by dmamontov** [comment]
@gitolicious In your case, a combination should help:

```yaml
button:
  - platform: template
    name: "Hold Space"
    id: hold_space
    on_press:
      then:
      - ble_keyboard.combination:
         id: myblekeyboard
         delay: 5
         keys:
           - 0x20
           - 0x20
```
