### ISSUE TITLE
[BUG] Error when installing

### ISSUE THREAD

**Issue by spaggi** [dmamontov/esphome-blekeyboard#35]
**Describe the bug**
When installing, I get the following error. Cleaning Installation doesn't help

```
INFO ESPHome 2024.6.6
INFO Reading configuration /config/esphome/esphome-web-274564.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-274564 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- NimBLE-Arduino @ 1.4.0
|-- ESP32 BLE Keyboard @ 0.3.2
|-- Improv @ 1.2.3
Linking .pioenvs/esphome-web-274564/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/esphome-web-274564/src/main.cpp.o:(.literal._Z5setupv+0x600): undefined reference to `vtable for esphome::esp32_ble_server::NimBLEServer'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/esphome-web-274564/src/main.cpp.o:(.literal._Z5setupv+0x604): undefined reference to `vtable for esphome::esp32_ble_server::NimBLEServer'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/esphome-web-274564/src/main.cpp.o:(.literal._Z5setupv+0x608): undefined reference to `vtable for esphome::esp32_ble_server::NimBLEServer'
collect2: error: ld returned 1 exit status
*** [.pioenvs/esphome-web-274564/firmware.elf] Error 1
========================= [FAILED] Took 95.16 seconds =========================
```

My YAML:
```

substitutions:
  name: esphome-web-274564
  friendly_name: BLEKeyboard

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

external_components:
  - source: github://dmamontov/esphome-blekeyboard

esp32:
  board: esp32dev
  framework:
    type: arduino

ble_keyboard:
  id: mamontech_keyboard
  name: "MamonTechKeyboard"
  manufacturer_id: "MamonTech"
  battery_level: 50
  reconnect: true
  buttons: true
  use_default_libs: false

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

esp32_improv:
  authorizer: none
```

**Please complete the following information:**
 - ESPHome version: 2024.6.6
 - ESP32
